# Generated by Django 6.1 on 2026-09-15 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_legacy_records(apps, schema_editor):
    Organization = apps.get_model("dispositivos", "Organization")
    organization, _ = Organization.objects.get_or_create(
        tax_id="LEGACY-001",
        defaults={
            "legal_name": "Legacy EcoEnergy Organization",
            "trade_name": "Legacy EcoEnergy",
            "contact": "",
        },
    )
    apps.get_model("dispositivos", "Zone").objects.filter(
        organization__isnull=True
    ).update(organization=organization)
    apps.get_model("dispositivos", "Device").objects.filter(
        organization__isnull=True
    ).update(organization=organization)


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('effective_minimum', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('effective_maximum', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('severity', models.CharField(max_length=30)),
                ('unit', models.CharField(default='kWh', max_length=20)),
                ('minimum', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('maximum', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('organization__legal_name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective')], max_length=20)),
                ('reason', models.TextField()),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('closed', 'Closed')], default='open', max_length=20)),
                ('planned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('actions_taken', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value_kwh', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(default='kWh', max_length=20)),
                ('measured_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20)),
                ('integration_name', models.CharField(blank=True, max_length=120)),
                ('deleted_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-measured_at',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('legal_name', models.CharField(max_length=150)),
                ('tax_id', models.CharField(max_length=20, unique=True)),
                ('trade_name', models.CharField(blank=True, max_length=150)),
                ('contact', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('legal_name',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rut', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ('organization__legal_name', 'name')},
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='dispositivo_status_ed9cbb_idx',
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_events', to='dispositivos.device'),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_rules', to='dispositivos.category'),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='dispositivos.alertrule'),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='dispositivos.device'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='dispositivos.device'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_measurements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_events', to='dispositivos.measurement'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='dispositivos.organization'),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='dispositivos.organization'),
        ),
        migrations.AddField(
            model_name='device',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='dispositivos.organization'),
        ),
        migrations.AddField(
            model_name='zone',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='dispositivos.organization'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['organization', 'status'], name='dispositivo_organiz_4e8195_idx'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_zone_name_per_organization'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='dispositivos.department'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='dispositivos.organization'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(assign_legacy_records, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='zone',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='dispositivos.organization'),
        ),
        migrations.AlterField(
            model_name='device',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='dispositivos.organization'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['device', 'measured_at'], name='dispositivo_device__4e706a_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_department_name_per_organization'),
        ),
    ]
