# Generated by Django 6.1 on 2026-09-28 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_alertevent_alertrule_department_maintenancerequest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertevent',
            options={'verbose_name': 'alert event', 'verbose_name_plural': 'alert events'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('organization__legal_name', 'name'), 'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('name',), 'verbose_name': 'device', 'verbose_name_plural': 'devices'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'verbose_name': 'maintenance request', 'verbose_name_plural': 'maintenance requests'},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ('-measured_at',), 'verbose_name': 'measurement', 'verbose_name_plural': 'measurements'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('legal_name',), 'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ('organization__legal_name', 'name'), 'verbose_name': 'zone', 'verbose_name_plural': 'zones'},
        ),
    ]
