# Generated by Django 6.1 on 2026-10-01 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_alter_alertevent_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertevent',
            options={'verbose_name': 'evento de alerta', 'verbose_name_plural': 'eventos de alerta'},
        ),
        migrations.AlterModelOptions(
            name='alertrule',
            options={'ordering': ('name',), 'verbose_name': 'regla de alerta', 'verbose_name_plural': 'reglas de alerta'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'categoría', 'verbose_name_plural': 'categorías'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('organization__legal_name', 'name'), 'verbose_name': 'departamento', 'verbose_name_plural': 'departamentos'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('name',), 'verbose_name': 'dispositivo', 'verbose_name_plural': 'dispositivos'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'verbose_name': 'solicitud de mantenimiento', 'verbose_name_plural': 'solicitudes de mantenimiento'},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ('-measured_at',), 'verbose_name': 'medición', 'verbose_name_plural': 'mediciones'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('legal_name',), 'verbose_name': 'organización', 'verbose_name_plural': 'organizaciones'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'perfil de usuario', 'verbose_name_plural': 'perfiles de usuario'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ('organization__legal_name', 'name'), 'verbose_name': 'zona', 'verbose_name_plural': 'zonas'},
        ),
    ]
